Adding all the rest (expect arm64 github build) to the workflow + some other fixes

diff --git a/.github/workflows/github_ci_dev.yml b/.github/workflows/github_ci_dev.yml
--- a/.github/workflows/github_ci_dev.yml
+++ b/.github/workflows/github_ci_dev.yml
@@ -37,43 +37,14 @@ jobs:
           fi
           echo "Running testpackage"
 
-  get_git_diff_check:
-    runs-on: ubuntu-latest
-    needs: get_git_diff
-    if: ${{ needs.get_git_diff.outputs.RUN_TP != 'False' }}
-    steps:
-      - name: Checking whether to run tests
-        run: |
-          echo "Running testpackage"
-
-  build_libraries_github:
-    # Build libraries for the current version of the docker image
-    # (to be used in any subsequent compilation and run jobs on said image)
-
-    runs-on: ubuntu-latest
-    container: ursg/vlasiator_ci:20250909_1
-
-    steps:
-      - uses: lukka/get-cmake@latest
-      - name: Checkout source
-        uses: actions/checkout@v4
-        with:
-          submodules: true 
-      - name: Install build dependencies
-        run: |
-          apt-get update
-          apt-get install -y g++ build-essential cmake make libopenmpi-dev openmpi-bin libboost-program-options-dev zstd
-      - name: Run library build script
-        run: ./fetch_and_build_libraries.sh
-      - name: Build libraries tar
-        run: tar --zstd -cf libraries-docker.tar.zstd libraries-docker/
-      - name: Upload libraries as artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: libraries-docker
-          path: libraries-docker.tar.zstd
-          retention-days: 5
-          if-no-files-found: error
+  # get_git_diff_check:
+  #   runs-on: ubuntu-latest
+  #   needs: get_git_diff
+  #   if: ${{ needs.get_git_diff.outputs.RUN_TP != 'False' }}
+  #   steps:
+  #     - name: Checking whether to run tests
+  #       run: |
+  #         echo "Running testpackage"
 
   testpackage:
     # Build Vlasiator with testpackage flags, on the carrington cluster
@@ -98,6 +69,7 @@ jobs:
             arch: pioneer
             compile_tp: false
     runs-on: ${{ matrix.runner }} 
+    needs: get_git_diff
     env:
       VLASIATOR_ARCH: ${{ matrix.arch }}
     steps:
@@ -149,7 +121,7 @@ jobs:
     - &runTP
       name: Run TP
       id: run
-      if: ${{ matrix.compile_tp }}
+      if: ${{ matrix.compile_tp && needs.get_git_diff.outputs.RUN_TP != 'False' }}
       run: |
         ./.github/workflows/slurm_run.sh "RUN_TP"
     - name: Scancel dangling job upon cancellation
@@ -195,157 +167,265 @@ jobs:
         retention-days: 5
         if-no-files-found: error
 
-    #
-  # build_libraries:
-  #   #Build libraries definition
-  #   # strategy: *strategy
-  #   if: false
-  #   # runs-on: ${{ matrix.runner }}
-  #   steps: &buildLibs
-  #     - *checksrc 
-  #     - *cleanup
-  #     - name: Run library build script ${{ matrix.arch }}
-  #       run: | 
-  #         export VLASIATOR_ARCH=${{ matrix.arch }}
-  #         ./.github/workflows/slurm_run.sh "BUILD_LIBS"
-  #     - name: Build libraries tar
-  #       run: tar -zcf libraries-${{ matrix.arch }}.tar.gz libraries-${{ matrix.arch }}/
-  #     - name: Upload libraries as artifact
-  #       uses: actions/upload-artifact@v4
-  #       with:
-  #         name: libraries-${{ matrix.arch }}
-  #         path: libraries-${{ matrix.arch }}.tar.gz
-  #         retention-days: 5
-  #         if-no-files-found: error
-  #     #
-  #
-  # alternative way to handle things
-  # build_libraries_hile_gpu:
-  #     runs-on: hile
-  #     strategy:
-  #       matrix: 
-  #         include:
-  #           - arch: hile_gpu
-  #
-  #     steps: *buildLibs
-  #
-  # build_TP_hile_gpu:
-  #     runs-on: hile
-  #     strategy:
-  #       matrix: 
-  #         include:
-  #           - arch: hile_gpu
-  #
-  #     needs: build_libraries_hile_gpu
-  #
-  #     steps: *buildTP
-  ##
-  #build_prod_debug:
-  #  # Build Vlasiator with production flags and all the debug flags enabled, on the HILE cluster using
-  #  # its AMD gpus
-  #
-  #  strategy: *strategy
-  #
-  #  runs-on: ${{ matrix.runner }}
-  #  steps:
-  #    - *checksrc
-  #    - *cleanup
-  #    - name: Make clean
-  #      run: VLASIATOR_ARCH=${{ matrix.arch }} make clean
-  #    - uses: ursg/gcc-problem-matcher@master
-  #    - name: Run library build script ${{ matrix.arch }}
-  #      run: | 
-  #        export VLASIATOR_ARCH=${{ matrix.arch }}
-  #        ./.github/workflows/slurm_run.sh "BUILD_LIBS"
-  #    - name: Unpack libraries
-  #      run: tar -zxf libraries-${{ matrix.arch }}.tar.gz
-  #
-  #    - name: Compile vlasiator 
-  #      run: |
-  #        export VLASIATOR_ARCH=${{ matrix.arch }}
-  #        ./.github/workflows/slurm_run.sh "COMPILE_PROD"
-  #
-  #    - *binaryVisible
-  #    - name: Upload testpackage binary
-  #      uses: actions/upload-artifact@v4
-  #      with:
-  #        name: vlasiator-prod-debug-${{ matrix.arch }}
-  #        path: vlasiator
-  #        if-no-files-found: error
-  #
-  #build_tools:
-      # Build vlsvdiff and vlsvextract for testpackage use
-      # NOTE is lacking libraries at the moment
-      # strategy: *strategy
-      #
-      # runs-on: ${{ matrix.runner }}
-      #
-      # steps:
-      #   - *checksrc
-      #   - *cleanup
-      #   - name: Make clean
-      #     run: VLASIATOR_ARCH=${{ matrix.arch }} make clean
-      #   - name: Run library build script ${{ matrix.arch }}
-      #     run: | 
-      #       export VLASIATOR_ARCH=${{ matrix.arch }}
-      #       ./.github/workflows/slurm_run.sh "BUILD_LIBS"
-      #   - uses: ursg/gcc-problem-matcher@master
-      #   - name: Compile tools 
-      #     run: |
-      #       export VLASIATOR_ARCH=${{ matrix.arch }}
-      #       ./.github/workflows/slurm_run.sh "BUILD_TOOLS"
-      #   - name: Upload tools binaries
-      #     uses: actions/upload-artifact@v4
-      #     with:
-      #       name: vlasiator-tools-${{ matrix.arch }}
-      #       path: |
-      #         vlsvextract_DP
-      #         vlsvdiff_DP
-      #         fluxfunction
-      #       if-no-files-found: error
-  #
-  # run_TP:
-  #     # Build vlsvdiff and vlsvextract for testpackage use
-  #     # NOTE is lacking libraries at the moment
-  #     strategy: *strategy
-  #
-  #     runs-on: ${{ matrix.runner }}
-  #
-  #     needs: [build_TP,build_tools]
-  #
-  #     steps:
-  #       - *ifCompileTP
-  #       - *checksrc
-  #       - *cleanup
-  #       - name: Make clean
-  #         run: VLASIATOR_ARCH=${{ matrix.arch }} make clean
-  #       - uses: ursg/gcc-problem-matcher@master
-  #
-  #Dummy job to be able to reuse the steps later
-  # _definitions:
-  #   runs-on: ubuntu-latest
-  #   if: false
-  #   steps:
-  #   - &checksrc
-  #     name: Checkout source
-  #     uses: actions/checkout@v4
-  #     with:
-  #       submodules: true
-  #   - &cleanup
-  #     name: Clean workspace
-  #     run: |
-  #       export VLASIATOR_ARCH=${{ matrix.arch }}
-  #       ./.github/workflows/slurm_run.sh "CLEANUP"
-  #   - &binaryVisible
-  #     name: Make sure the output binary is visible in lustre
-  #     uses: nick-fields/retry@v3
-  #     with:
-  #       timeout_seconds: 15
-  #       max_attempts: 3
-  #       retry_on: error
-  #       command: ls vlasiator
-  #   # - &ifCompileTP
-  #   #   name: Check whether to run this step 
-  #   #   if: ${{ matrix.compile_tp }}
-  #   #   run: echo "Running"
+  build_libraries_github:
+    # Build libraries for the current version of the docker image
+    # (to be used in any subsequent compilation and run jobs on said image)
+
+    runs-on: ubuntu-latest
+    container: ursg/vlasiator_ci:20250909_1
+
+    steps:
+      - uses: lukka/get-cmake@latest
+      - *checkoutSource
+      - &githubLibs
+        name: Install build dependencies
+        run: |
+          apt-get update
+          apt-get install -y g++ build-essential cmake make libopenmpi-dev openmpi-bin libboost-program-options-dev zstd
+      - name: Run library build script
+        run: ./fetch_and_build_libraries.sh
+      - name: Build libraries tar
+        run: tar --zstd -cf libraries-docker.tar.zstd libraries-docker/
+      - name: Upload libraries as artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: libraries-docker
+          path: libraries-docker.tar.zstd
+          retention-days: 5
+          if-no-files-found: error
+
+  build_libraries_arm64:
+    # Build libraries on macos with M1 hardware, to test both macOS and aarch64 compatibility
+    runs-on: ubuntu-24.04-arm
+
+    steps:
+      - *checkoutSource
+      - *githubLibs
+      - name: Run library build script
+        run: |
+          . ./fetch_and_build_libraries.sh arm64
+      - name: Build libraries tar
+        run: tar --zstd -cf libraries-arm64.tar.zstd libraries-arm64
+      - name: Upload libraries as artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: libraries-arm64
+          path: libraries-arm64.tar.zstd
+          retention-days: 5
+          if-no-files-found: error
+      - name: Make clean
+        run: VLASIATOR_ARCH=github_actions_arm64 make clean
+      - name: Compile vlasiator (Release build)
+        run: |
+          VLASIATOR_ARCH=github_actions_arm64 make -j 4
+  #add build arm
+  build_github:
+    # Build Vlasiator with production flags
+    strategy:
+      matrix:
+        compile_flags: ["prod","prod_debug","ord1_time","ord1_space"]
+    runs-on: ubuntu-latest
+    container: ursg/vlasiator_ci:20250909_1
+    needs: build_libraries_github
+    env:
+      VLASIATOR_ARCH: github_actions
+    steps:
+    - *checkoutSource
+    - name: Download libraries
+      uses: actions/download-artifact@v5
+      with:
+        name: libraries-docker
+    - name: Unpack libraries
+      run: tar --zstd -xf libraries-docker.tar.zstd
+    - uses: ursg/gcc-problem-matcher@master
+
+    - name: Compile vlasiator (Release build)
+      run: |
+        make clean
+        if [[ ${{ matrix.compile_flags }}=="prod" ]]; then
+          make -j 3
+        else if [[ ${{ matrix.compile_flags }}=="ord1_time" ]]; then
+          COMPFLAGS="-DFS_1ST_ORDER_TIME" make -j 3
+        else if [[ ${{ matrix.compile_flags }}=="ord1_time" ]]; then
+          COMPFLAGS="-DFS_1ST_ORDER_SPACE" make -j 3
+        else if [[ ${{ matrix.compile_flags }}=="ord1_time" ]]; then
+          COMPFLAGS="-DDEBUG_VLASIATOR -DDEBUG_SOLVERS -DDEBUG_IONOSPHERE -DDEBUG_SPATIAL_CELL -DDEBUG_VMESH -DDEBUG_VBC -DDEBUG_ACC" make -j 3
+        else
+          echo "Unknown compile_flags entry \"${{ matrix.compile_flags }}\" !"
+        fi
+
+    - name: Upload release binary
+      uses: actions/upload-artifact@v4
+      with:
+        name: vlasiator-${{ matrix.compile_flags }}
+        path: vlasiator
+        if-no-files-found: error
+
+  build_ionosphereTests:
+    # Build IonosphereSolverTests miniApp
+    runs-on: ubuntu-latest
+    container: ursg/vlasiator_ci:20250909_1
+    needs: build_libraries_github
+    steps:
+    - name: Checkout source
+      uses: actions/checkout@v4
+      with:
+        submodules: true
+          #    - name: Download libraries
+          #      uses: actions/download-artifact@v5
+          #      with:
+          #        name: libraries
+          #    - name: Unpack libraries
+          #      run: tar --zstd -xf libraries.tar.zstd
+          #    - uses: ursg/gcc-problem-matcher@master
+    - name: Download libraries
+      uses: actions/download-artifact@v5
+      with:
+        name: libraries-docker
+    - name: Unpack libraries
+      run: tar --zstd -xf libraries-docker.tar.zstd
+    - name: Compile ionosphereSolverTests
+      run: |
+        cd mini-apps/ionosphereSolverTests/
+        VLASIATOR_ARCH=github_actions make -j 3
+    - name: Upload ionosphereTest binaries
+      uses: actions/upload-artifact@v4
+      with:
+        name: ionosphereTests
+        path: |
+          mini-apps/ionosphereSolverTests/main
+          mini-apps/ionosphereSolverTests/differentialFlux
+          mini-apps/ionosphereSolverTests/sigmaProfiles
+        if-no-files-found: error
+
+  run_ionosphere_LFMtest:
+    runs-on: ubuntu-latest
+    container: ursg/vlasiator_ci:20250909_1
+    needs: [build_ionosphereTests, get_git_diff_check]
+    steps:
+    - name: Checkout source
+      uses: actions/checkout@v4
+      with:
+        submodules: false
+    - name: Download ionosphereTests
+      uses: actions/download-artifact@v5
+      with:
+        name: ionosphereTests
+    - name: Set up Python
+      uses: actions/setup-python@v3
+    - name: Install uv
+      uses: astral-sh/setup-uv@v6
+    - name: install Gnuplot
+      run: |
+        apt update
+        apt -y install gnuplot-nox
+    - name: checkout Analysator
+      run: |
+        cd mini-apps/ionosphereSolverTests/
+        git clone https://github.com/fmihpc/analysator
+        export TMPDIR=$RUNNER_TEMP
+        uv venv CI_env
+        . CI_env/bin/activate
+        uv pip install --editable analysator
+    - name: Run LFMtest
+      run: |
+        chmod +x $GITHUB_WORKSPACE/main
+        cd mini-apps/ionosphereSolverTests/
+        OMP_NUM_THREADS=1 $GITHUB_WORKSPACE/main -N 2000 -r 40 90 -r 50 90 -r 60 80 -sigma 10 -fac merkin2010 -gaugeFix equator45 -o LFMtest.vlsv -maxIter 10000
+        export TMPDIR=$RUNNER_TEMP
+        . CI_env/bin/activate
+        export PTNONINTERACTIVE=1
+        python3 ./lfmformat.py LFMtest.vlsv > lfmtest.dat
+        ./plot_LFMtest.gp
+    - name: Run atmospheric profile test
+      run: |
+        chmod +x $GITHUB_WORKSPACE/sigmaProfiles
+        cd mini-apps/ionosphereSolverTests/
+        $GITHUB_WORKSPACE/sigmaProfiles 1e6 1.16046e7 > atmosphere.dat
+        $GITHUB_WORKSPACE/sigmaProfiles 1e6 1.16046e8 > atmosphere10.dat
+        $GITHUB_WORKSPACE/sigmaProfiles 1e6 1.16046e9 > atmosphere100.dat
+        ./plotAtmosphere.gp
+    - name: Upload ionosphereTest result images
+      uses: actions/upload-artifact@v4
+      with:
+        name: ionosphereTestResults
+        path: |
+          mini-apps/ionosphereSolverTests/LFMtest.png
+          mini-apps/ionosphereSolverTests/atmosphere.png
+        if-no-files-found: error
+
+  check_cfg_files:
+    runs-on: ubuntu-latest
+    container: ursg/vlasiator_ci:20250909_1
+    needs: [build_libraries_github, build_prod]
+    steps:
+    - name: Checkout source
+      uses: actions/checkout@v4
+      with:
+        submodules: false
+    - name: Download libraries
+      uses: actions/download-artifact@v5
+      with:
+        name: libraries-docker
+    - name: Unpack libraries
+      run: tar --zstd -xf libraries-docker.tar.zstd
+    - name: Download release binary
+      uses: actions/download-artifact@v5
+      with:
+        name: vlasiator-release
+    - name: Make release binary executable
+      run: |
+        chmod +x $GITHUB_WORKSPACE/vlasiator
+    - name: Check cfg files in projects/
+      run: |
+        retval=0
+        set +e
+        for cfg in `find projects -name \*.cfg`; do
+          echo -n "Testing cfg file $cfg... "
+          PRINT_ONLY_ERRORS=true LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GITHUB_WORKSPACE/libraries-docker/lib tools/check_vlasiator_cfg.sh $GITHUB_WORKSPACE/vlasiator $cfg 2>&1 > cfgtest.out
+          if [ $? != 0 ]; then
+            if `echo $cfg | grep -sq unsupported`; then
+              echo "failed (unsurprising)"
+            else
+              echo "FAILED:";
+              cat cfgtest.out;
+              retval=127
+            fi
+          else
+            echo "ok."
+          fi;
+        done
+        exit $retval
+    - name: Check cfg files in samples/
+      run: |
+        retval=0
+        set +e
+        for cfg in `find samples -name \*.cfg`; do
+          echo -n "Testing cfg file $cfg... "
+          PRINT_ONLY_ERRORS=true LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GITHUB_WORKSPACE/libraries-docker/lib tools/check_vlasiator_cfg.sh $GITHUB_WORKSPACE/vlasiator $cfg 2>&1 > cfgtest.out
+          if [ $? != 0 ]; then
+            echo "FAILED:";
+            cat cfgtest.out;
+            retval=127
+          else
+            echo "ok."
+          fi;
+        done
+        exit $retval
+    - name: Check cfg files in testpackage/
+      run: |
+        retval=0
+        set +e
+        for cfg in `find testpackage -name \*.cfg`; do
+          echo -n "Testing cfg file $cfg... "
+          PRINT_ONLY_ERRORS=true LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GITHUB_WORKSPACE/libraries-docker/lib tools/check_vlasiator_cfg.sh $GITHUB_WORKSPACE/vlasiator $cfg 2>&1 > cfgtest.out
+          if [ $? != 0 ]; then
+            echo "FAILED:";
+            cat cfgtest.out;
+            retval=127
+          else
+            echo "ok."
+          fi;
+        done
+        exit $retval
 
